### ISSUE TITLE
Regression between old and new version for loading parquet

### ISSUE THREAD

**Issue by Shogan** [multiprocessio/dsq#15]
Previously with an older release of dsq I could do a basic SQL select on a parquet file.

With the latest release (`0.2.0`), I get this error:

`panic: Missing type equality condition for unknown merge.`

Command:

```
./dsq ~/Downloads/part-00030.snappy.parquet "SELECT * FROM {}"
```

If you can't reproduce this easily I can see if I can get a sample parquet file together and attached to this.

Stacktrace:

```
goroutine 1 [running]:
github.com/multiprocessio/datastation/runner.shapeMerge({{0x4c4111c, 0x7}, 0x0, 0x0, 0x0, 0x0}, {{0x4c4111c, 0x7}, 0x0, 0x0, ...})
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:248 +0x648
github.com/multiprocessio/datastation/runner.objectMerge({0x4bd1da0}, {0x4bd1da0})
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:209 +0x1b9
github.com/multiprocessio/datastation/runner.shapeMerge({{0x4c3f476, 0x6}, 0x0, 0xc000010168, 0x0, 0x0}, {{0x4c3f476, 0x6}, 0x0, 0xc000010198, ...})
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:232 +0x115
github.com/multiprocessio/datastation/runner.getArrayShape({0x7ffeefbff919, 0x30}, {0xc0005183c0, 0x3, 0x6}, 0x16)
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:268 +0x3e5
github.com/multiprocessio/datastation/runner.GetShape({0x7ffeefbff919, 0x4ac43e0}, {0x4ad1700, 0xc00051c4f8}, 0x0)
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:277 +0x245
github.com/multiprocessio/datastation/runner.ShapeFromFile({0xc0005bb570, 0x4adfe60}, {0x7ffeefbff919, 0x30}, 0x2710, 0x7ffeefbff919)
	/Users/runner/go/pkg/mod/github.com/multiprocessio/datastation/runner@v0.0.0-20220121201025-e665cd7ac0fc/shape.go:328 +0x16c
main.getShape({0xc0005bb570, 0x30}, {0x7ffeefbff919, 0x30})
	/Users/runner/work/dsq/dsq/main.go:46 +0x4e
main.main()
	/Users/runner/work/dsq/dsq/main.go:202 +0xac7
```

**Comment by eatonphil** [comment]
Aha! Yes please do send me a sample. I thought that code path wasn't possible.

**Comment by eatonphil** [comment]
Hey @Shogan ping on a sample to help me reproduce this :/

**Comment by eatonphil** [comment]
What I'm going to do in the meantime is drop this panic. It's demonstrating a real bug but maybe you don't care about this particular column.

Instead it will just log some info about the column and you still won't be able to query that column until I fix the bug.

https://github.com/multiprocessio/datastation/pull/162 this pr is where the main fix happens.

**Comment by eatonphil** [comment]
I'm having trouble reproducing this though. In Github Actions this test passes, as does it on my MBP and Fedora Linux dev machine.

I also tried building dsq and running the tests in an `archlinux` container and the tests passed.

Can you tell me any more about your machine/environment? I'm surprised it worked for you before and now breaks.

**Comment by Shogan** [comment]
> Hey @Shogan ping on a sample to help me reproduce this :/

Hi @eatonphil , sorry it took me so long - I was on vacation for a while and not checking notifications. I've had a look at the parquet I was querying and unfortunately I can't provide it here easily as it has sensitive data.

However in trying to load it up and edit it to remove said data, using viewer tool I got an exception about INT96 being unsupported. So this parquet data I'm working with uses INT96. Could that be an issue? I believe it is incompatible with avro.

I used the same version of dsq that I used when I started this thread to load some other parquet file examples I found [here](https://github.com/kaysush/sample-parquet-files) and it worked fine for these.

**Comment by eatonphil** [comment]
> However in trying to load it up and edit it to remove said data, using viewer tool I got an exception about INT96 being unsupported. So this parquet data I'm working with uses INT96. Could that be an issue? I believe it is incompatible with avro.

Ok I'll try making a dataset with INT96 in it and see if that causes an issue.

But also if you don't need that column right now newer versions of dsq won't crash when this happens. They'll just not be able to load that column for querying.

**Comment by Shogan** [comment]
> > However in trying to load it up and edit it to remove said data, using viewer tool I got an exception about INT96 being unsupported. So this parquet data I'm working with uses INT96. Could that be an issue? I believe it is incompatible with avro.
> 
> Ok I'll try making a dataset with INT96 in it and see if that causes an issue.
> 
> But also if you don't need that column right now newer versions of dsq won't crash when this happens. They'll just not be able to load that column for querying.

Nice! Confirmed version 0.6.0 works. Thanks @eatonphil 🎉

**Comment by grawlinson** [comment]
> I'm having trouble reproducing this though. In Github Actions this test passes, as does it on my MBP and Fedora Linux dev machine.
> 
> I also tried building dsq and running the tests in an `archlinux` container and the tests passed.
> 
> Can you tell me any more about your machine/environment? I'm surprised it worked for you before and now breaks.

I can reproduce it on two different machines both running Arch Linux, both Intel & AMD CPUs with go 1.18.

Basically just running in a clean chroot (based on systemd-nspawn) following our [Go](https://wiki.archlinux.org/title/Go_package_guidelines#Flags_and_build_options) packaging guidelines, so the flags could be a thing (but I doubt it).

I've currently skipped the failing parquet tests.

**Comment by eatonphil** [comment]
Gotcha! It's the -buildmode=pie flag that is exposing this crash (I don't know whether or not to say it's _causing_ the crash).

I'm going to make a separate issue about -buildmode=pie. I don't know whether I'll be able to fix it though.
