### ISSUE TITLE
panic: runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by cbcye** [multiprocessio/dsq#98]
**When i run the following commend** 
dsq --pretty ~/Downloads/test\ 202208.xlsx ~/Downloads/test\ 202207.xlsx ~/Downloads/test\ 202207.xlsx"select count(*) from (select * from {0} union select * from {1} union select * from {2})"

**Got the following error**
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.runQuery({0x7ffeefbffc37?, 0x0?}, 0xc001525b58, 0xc001525ae8, 0xc000040b90, {0xc0001cbe40, 0x2, 0x5cb98d6?}, 0x0?)
	github.com/multiprocessio/dsq/main.go:256 +0x565
main._main()
	github.com/multiprocessio/dsq/main.go:681 +0x1aa5
main.main()
	github.com/multiprocessio/dsq/main.go:685 +0x19

**Versions**
 - OS: [Mac]
- Shell: [bash]
 - dsq version: [e.g. 0.22]

**Additional context, screenshots**
If I just link 2 files is all right, Could we extend to bigger data size support?

**Comment by cbcye** [comment]
My mistake, link the same files
